CREATE TABLE toilets (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         source VARCHAR(100) NOT NULL,
                         source_id VARCHAR(255) NOT NULL,

                         name VARCHAR(255),
                         latitude DOUBLE PRECISION NOT NULL,
                         longitude DOUBLE PRECISION NOT NULL,

                         toilet_type VARCHAR(100),
                         accessibility_status VARCHAR(100),
                         comments TEXT,
                         source_modified_at TIMESTAMP WITH TIME ZONE,

                         CONSTRAINT uq_toilets_source_source_id
                             UNIQUE (source, source_id),

                         CONSTRAINT chk_toilets_latitude
                             CHECK (latitude BETWEEN -90 AND 90),

                         CONSTRAINT chk_toilets_longitude
                             CHECK (longitude BETWEEN -180 AND 180)
);