spring.application.name=toilapp

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/toilapp}
spring.datasource.username=${DB_USERNAME:toilapp}
spring.datasource.password=${DB_PASSWORD:toilapp_dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false